#ifndef __LCVM_CORE_EXCEPTIONS_H__
#define __LCVM_CORE_EXCEPTIONS_H__

#define LCVM_EXCEPTION_NONE 0

#define LCVM_EXCEPTION_OUT_OF_PROGRAM 1
#define LCVM_EXCEPTION_OUT_OF_MEMORY 2
#define LCVM_EXCEPTION_OPSTACK_OVERFLOW 3
#define LCVM_EXCEPTION_OPSTACK_EMPTY 4
#define LCVM_EXCEPTION_RETSTACK_OVERFLOW 5
#define LCVM_EXCEPTION_RETSTACK_EMPTY 6

#define LCVM_EXCEPTION_WRITE_PROTECTION 7
#define LCVM_EXCEPTION_MEMORY_OUT_OF_RANGE 8
#define LCVM_EXCEPTION_ROM_OUT_OF_RANGE 9

#define LCVM_EXCEPTION_BUFFER_OUT_OF_RANGE 10
#define LCVM_EXCEPTION_BUFFER_POINTER_ERROR 11

#define LCVM_EXCEPTION_UNKNOWN_INSTRUCTION 16

#define LCVM_EXCEPTION_INVALID_SYSCALL_ID 17
#define LCVM_EXCEPTION_INVALID_SYSCALL_PARAM 18

#define LCVM_EXCEPTION_INVALID_INSTRUCTION_PARAM 19

#define LCVM_EXCEPTION_IO_ACCESS_ERROR 127
#define LCVM_EXCEPTION_INTERNAL_ERROR 128

#define LCVM_EXCEPTION_HALT 255

#endif